version: "3" #docker-compose version
services: #the containers in the network
  database:
    image: postgres #if using an existing image
    restart: always #what to do if container crashes
    env_file: ./database.env
    volumes: # mapping the host folder to the data folder in the container - to persist the data
      - /var/lib/docker/volumes/postgres_db_nlp_compare/_data:/var/lib/postgresql/data/
  voila_server:
    build: .
    image: text_labeller_voila
    env_file: ./database.env
    ports: #map ports (host:container)
      - 8866:8866
    depends_on: # other containers it needs in order to run
      - database
    restart: always




